title: frank coding experiments
description: tools for distant pairs and swarms of software engineers, each in isolation, working from home
github_username: fgenolini
twitter_username: fgenolini
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
